import type { Viewport } from 'next'
import { TRPCReactProvider } from '@/trpc/react'

import '@/styles/globals.css'

import { Main } from '@/components/ui'
import GlobalTitle from './_components/title'

const DEFAULT_TITLE = 'lib'

export const metadata = {
  manifest: '/manifest.json',
  description: 'Generated by create-t3-app',
  icons: {
    icon: '/favicon.png',
    shortcut: '/favicon.png',
    apple: '/icon.png',
  },
  title: DEFAULT_TITLE,
}

export const viewport: Viewport = {
  themeColor: '#193549',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body>
        <div className='flex min-h-screen flex-col bg-cb-dark-blue text-cb-white'>
          <TRPCReactProvider>
            <Main className='container mx-auto flex max-w-screen-md flex-col p-4 md:px-0'>
              <div className='flex flex-grow flex-col space-y-4'>
                <GlobalTitle>{DEFAULT_TITLE}</GlobalTitle>
                {children}
              </div>
            </Main>
          </TRPCReactProvider>
        </div>
      </body>
    </html>
  )
}
